"""empty message

Revision ID: 1a6a2ea1282e
Revises: b0be44dbb94e
Create Date: 2025-08-05 08:16:00.719719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6a2ea1282e'
down_revision = 'b0be44dbb94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_order', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
