"""Add Customer model for LeafTrade customer caching

Revision ID: 3774dce90315
Revises: fcd1f6f22ff6
Create Date: 2025-08-01 12:26:52.770436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3774dce90315'
down_revision = 'fcd1f6f22ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leaftrade_customer_id', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leaftrade_customer_id')
    )
    with op.batch_alter_table('location_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('unique_location_mapping'), type_='unique')
        batch_op.create_unique_constraint('unique_location_mapping', ['customer_id', 'biotrack_vendor_id'])
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])
        batch_op.drop_column('room_name')
        batch_op.drop_column('vendor_name')
        batch_op.drop_column('location_name')
        batch_op.drop_column('leaftrade_location_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leaftrade_location_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('location_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vendor_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('room_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_location_mapping', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_location_mapping'), ['leaftrade_location_id', 'biotrack_vendor_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('customer_id')

    op.drop_table('customer')
    # ### end Alembic commands ###
