"""Add status tracking and error logging to trip orders

Revision ID: 454acb38516c
Revises: 9d6083ab4a86
Create Date: 2025-11-10 07:56:47.147850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454acb38516c'
down_revision = '9d6083ab4a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('general_error', sa.Text(), nullable=True))

    with op.batch_alter_table('trip_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
    
    # Set default status for existing trip orders
    op.execute("UPDATE trip_order SET status = 'pending' WHERE status IS NULL")
    
    # Set started_at to created_at for existing trip executions (if created_at exists)
    op.execute("""
        UPDATE trip_executions 
        SET started_at = created_at 
        WHERE started_at IS NULL AND created_at IS NOT NULL
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_order', schema=None) as batch_op:
        batch_op.drop_column('error_message')
        batch_op.drop_column('status')

    with op.batch_alter_table('trip_executions', schema=None) as batch_op:
        batch_op.drop_column('general_error')
        batch_op.drop_column('started_at')

    # ### end Alembic commands ###
