"""remove_customer_fields_from_trip_order

Revision ID: 5231c6de8e30
Revises: e89537f39501
Create Date: 2025-09-04 10:43:06.635978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5231c6de8e30'
down_revision = 'e89537f39501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('email_invoice', sa.Boolean(), nullable=True),
    sa.Column('email_manifest', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_customer_contacts_vendor'))

    op.drop_table('customer_contacts')
    with op.batch_alter_table('trip_order', schema=None) as batch_op:
        batch_op.drop_column('customer_location')
        batch_op.drop_column('customer_name')

    with op.batch_alter_table('trip_order_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_trip_order_docs_trip_order'))
        batch_op.drop_constraint(batch_op.f('unique_trip_order_document_type'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_order_documents', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_trip_order_document_type'), ['trip_order_id', 'document_type'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_trip_order_docs_trip_order'), ['trip_order_id'], unique=False)

    with op.batch_alter_table('trip_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('customer_location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    op.create_table('customer_contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contact_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_invoice', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_manifest', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], name=op.f('customer_contacts_vendor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_contacts_pkey'))
    )
    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_customer_contacts_vendor'), ['vendor_id'], unique=False)

    op.drop_table('customer_contact')
    # ### end Alembic commands ###
