"""Add GlobalPreference table for finished goods report settings

Revision ID: 8c5c2e8ad6ed
Revises: cfbba42b5404
Create Date: 2025-10-27 13:05:41.963129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5c2e8ad6ed'
down_revision = 'cfbba42b5404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preference_key', sa.String(length=255), nullable=False),
    sa.Column('preference_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('preference_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_preference')
    # ### end Alembic commands ###
