"""Rename route_instructions to route_data for OpenAI JSON storage

Revision ID: b0be44dbb94e
Revises: 3774dce90315
Create Date: 2025-08-02 09:13:19.127384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0be44dbb94e'
down_revision = '3774dce90315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_data', sa.Text(), nullable=True))
        batch_op.drop_column('route_instructions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_instructions', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('route_data')

    # ### end Alembic commands ###
