"""Add approximate_start_time and delivery_date to Trip model

Revision ID: c159292fbe69
Revises: 1a6a2ea1282e
Create Date: 2025-08-05 10:10:00.875418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c159292fbe69'
down_revision = '1a6a2ea1282e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approximate_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivery_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('approximate_start_time')

    # ### end Alembic commands ###
