"""added trip execution

Revision ID: cfbba42b5404
Revises: 76b2e76642bf
Create Date: 2025-10-22 11:22:50.704578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfbba42b5404'
down_revision = '76b2e76642bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_executions',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('job_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('execution_status')

    op.drop_table('trip_executions')
    # ### end Alembic commands ###
