"""Add APIRefreshLog model for tracking API refresh timestamps

Revision ID: fcd1f6f22ff6
Revises: 83a6549add56
Create Date: 2025-08-01 10:10:54.951346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd1f6f22ff6'
down_revision = '83a6549add56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_refresh_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=50), nullable=False),
    sa.Column('last_refresh', sa.DateTime(), nullable=True),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_name', name='unique_api_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_refresh_log')
    # ### end Alembic commands ###
